### ISSUE TITLE
Add Redsys / Payment Gateway API

### ISSUE THREAD

**Issue by miraclebg** [IonicaBizau/made-in-bulgaria#16]
The following API is a 2021 rewrite of the original Redsys payment gateway API to communicate to most spanish banks using the service (Sabadel, Caixa, etc).

Written with PHP / composer.

Author: Martin Kovachev <miracle@nimasystems.com>, Github profile: https://github.com/miraclebg
Link: https://github.com/payin7-payments/redsys-hmac256-api

**Comment by IonicaBizau** [comment]
Please create pull requests for these. :)
