### ISSUE TITLE
Add CentroUI

### ISSUE THREAD

**Issue by oneturkmen** [IonicaBizau/made-in-bulgaria#8]
> CentroUI is a set of reusable and extendable UI components and utilities for building interfaces for WebVR applications. Based on React VR, CentroUI gives developers with plug-and-play text input controls, cards, lists, navigation items and grids, all built with cross-device and cross-browser compatibility to ensure consistent experience with any environment and device.

In short: Twitter Bootstrap-like library, but for VR applications (based on ReactVR).

- Author is Hristo Georgiev ([profile](https://github.com/hggeorgiev))
- Link is [here](https://github.com/hggeorgiev/CentroUI)

**Comment by IonicaBizau** [comment]
Please create a PR with the changes.
